// Static Generation without data

import Head from "next/head";
// import styles from "../styles/Home.module.css";
import styled from "styled-components";

const Div = styled.div`
  width: 60%;
  margin: 0 auto;

  p {
    color: green;
  }
`;

export default function Home() {
  return (
    <Div>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Getting Started</h1>
      <p>Welcome to the Next.js documentation!</p>
      <p>
        If you're new to Next.js we recommend that you start with the learn
        course.
      </p>
    </Div>
  );
}
